# Generated by Django 3.1.2 on 2020-10-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussinesscontact',
            name='businessDir',
        ),
        migrations.RemoveField(
            model_name='bussinesscontact',
            name='businessUnit',
        ),
        migrations.RemoveField(
            model_name='bussinesscontact',
            name='businessWeb',
        ),
        migrations.RemoveField(
            model_name='bussinesscontact',
            name='description',
        ),
        migrations.AddField(
            model_name='bussinesscontact',
            name='businessComment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='bussinesscontact',
            name='businessEmail',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Email'),
        ),
    ]
