# Generated by Django 3.1.2 on 2020-11-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0002_auto_20201030_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinesscontact',
            name='businessEmail',
            field=models.EmailField(default='Null', max_length=100, verbose_name='Correo'),
            preserve_default=False,
        ),
    ]
